[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; N16R8 - 16MB flash, 8MB PSRAM
board_upload.flash_size = 16MB
board_hardware.psram = opi8m
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

; Libraries
lib_deps =
    bblanchon/ArduinoJson @ ^7.3.1
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA@3.1.7

; OTA partition scheme
board_build.partitions = min_spiffs.csv

; Serial monitors
monitor_speed = 115200